### ISSUE TITLE
Error when running fs check

### ISSUE THREAD

**Issue by censey** [rohitcoder/hawk-eye#2]
Hello,
I am just trying to test the current version on a few documents.  This is the outputs I see after the files are processed. Just after "Now, lets look at findings!"

Traceback (most recent call last):
  File "/opt/homebrew/bin/hawk_scanner", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/hawk_scanner/main.py", line 116, in main
    records_mini = ', '.join(result['matches']) if len(result['matches']) < 25 else ', '.join(result['matches'][:25]) + f" + {len(result['matches']) - 25} more records"
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, tuple found

**Comment by rohitcodergroww** [comment]
Hi @censey thanks for using Hawk-eye

Can you run this with ``--debug`` flag and post output or screenshot here

**Comment by censey** [comment]
<img width="1256" alt="Screenshot 2024-01-26 at 1 16 38 PM" src="https://github.com/rohitcoder/hawk-eye/assets/24660392/e876e3ed-fe99-467c-a9d5-d742e44fbbc4">


I don't see the process go past this point.  I left it running for an hour without any progress.
This is on a Mac btw.

**Comment by censey** [comment]
Its taking a really long time to run but is parsing the various patterns.  I will try to wait it out.  Been hours for a single 1mb file.

**Comment by rohitcoder** [comment]
@censey This shouldn't be happening, i just checked this with bunch of pdfs, zip and docx. It's working fine with latest version. Can you tell me what kind of file you are scanning and possibly screenshot or logs with `--debug` flag?

**Comment by censey** [comment]
Ok.  I removed the xlsx file I was testing with and added a very simple word doc.  That ran flawlessly.  Something in this xls was causing all kinds of issues.   It was a large document with several tabs and 2k plus columns.   Some nested json in some of the fields too.

**Comment by rohitcoder** [comment]
Hey @censey 

Let me know, if you still find this issue relevant, then I'll look into this. Otherwise, I will be closing this. If possible please attach a sample file for debugging purpose, after removing sensitive data from it.
